// Action types
export const TYPES = {
  REQUESTED_DOG: 'REQUESTED_DOG',
  REQUESTED_DOG_SUCCEEDED: 'REQUESTED_DOG_SUCCEEDED',
  REQUESTED_DOG_FAILED: 'REQUESTED_DOG_FAILED',
  FETCHED_DOG: 'FETCHED_DOG'
};
